### ISSUE TITLE
Wrong entry in table for Method Properties

### ISSUE THREAD

**Issue by MBuchalik** [dirkriehle/adap-course#11]
@andreas-bauer @georg-schwarz 
In [ADAP C02 - Method Properties.pdf](https://github.com/dirkriehle/adap-course/blob/master/Generated/Lecture%20slides/ADAP%20C02%20-%20Method%20Properties.pdf) on slide 4, you will see that there is an entry called "primitive" in the "Inheritance" column. I believe that this should be called "Hook", or am I missing something?

**Comment by dirkriehle** [comment]
Correct, thanks!
